"""
Command line tool to create tasks.txt, the description of how individual tracks are combined into tasks.
First argument is the number of tracks per task.
Second argument the number of tasks to include.
third argument is whether the first task should be duplicated (babbling phase)
fourth argument is track_defs.txt, normally autogenerated. If omitted, it is assumed to lie in ./track_defs.txt
Example calls:
python3 create_tasks.py 4 5 yes > tasks.txt
python3 create_tasks.py 1 150 no > tasks.txt
python3 create_tasks.py 1 150 no ./track_defs.txt  > tasks.txt
"""

import itertools ;
import sys ;

tracks_per_task = int(sys.argv[1]) ;
nr_tasks = int(sys.argv[2]) ;
dup = sys.argv[3] ;
datafile = "./track_defs.txt" if len(sys.argv) == 4 else sys.argv[4] ;

track_names = [f"track_{i}" for i, line in enumerate([l for l in open(datafile,"r").readlines() if len(l) > 1 ])] ;

tracks = [] ;
tasks_done = 0 ;

for i,new_track in enumerate(track_names):
  tracks.append(new_track) ;
  if i >= tracks_per_task:
    tracks = tracks[1:] ;
  if i >= tracks_per_task-1:
    loops = 2 if tasks_done == 0 and dup=="yes" else 1 ;
    for l in range(loops):
      for t in tracks: print(t, end = " ") ;
      print() ;
    tasks_done += 1 ;
    if tasks_done >= nr_tasks: break ;
 
